
var products = [{
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "images/No_Image.png",
},
//Apple
{
    "id": 1,
    "title": "iPhone 12 mini",
    "price": 157399,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 131.5 x 64.2 x 7.4 mm (5.18 x 2.53 x 0.29 in) 135 g (4.76 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 625 nits (HBM), 1200 nits (peak) 5.4 inches, 71.9 cm2 (~85.1% screen-to-body ratio)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 12 mini.png",
},
{
    "id": 2,
    "title": "iPhone 12",
    "price": 224900,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in) 164 g (5.78 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 625 nits (HBM), 1200 nits (peak) 6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio) 1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 12.png",
},
{
    "id": 3,
    "title": "iPhone 12 pro",
    "price":  258999, 
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in) 189 g (6.67 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 12 pro.png",
},
{
    "id": 4,
    "title": "iPhone 12 pro max",
    "price": 240999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 160.8 x 78.1 x 7.4 mm (6.33 x 3.07 x 0.29 in) 228 g (8.04 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 12 pro max.png",
},
{
    "id": 5,
    "title": "iPhone 13 mini",
    "price": 304999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 131.5 x 64.2 x 7.7 mm (5.18 x 2.53 x 0.30 in) 141 g (4.97 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 13 mini.png",
},
{
    "id": 6,
    "title": "iPhone 13",
    "price": 179999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in) 174 g (6.14 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 13.png",
},
{
    "id": 7,
    "title": "iPhone 13 pro",
    "price": 344999,
    "description":"GSM / CDMA / HSPA / EVDO / LTE / 5G 146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in) 204 g (7.20 oz) Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 13 pro.png",
},
{
    "id": 8,
    "title": "iPhone 13 pro max",
    "price": 369600,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 160.8 x 78.1 x 7.7 mm (6.33 x 3.07 x 0.30 in) 240 g (8.47 oz) Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 13 pro max.png",
},
{
    "id": 9,
    "title": "iPhone 14",
    "price": 337900,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 146.7 x 71.5 x 7.8 mm (5.78 x 2.81 x 0.31 in 172 g (6.07 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 14.png",
},
{
    "id": 10,
    "title": "iPhone 14 plus",
    "price": 409999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 160.8 x 78.1 x 7.8 mm (6.33 x 3.07 x 0.31 in) 203 g (7.16 oz) Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak) ",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 14 plus.png",
},
{
    "id": 11,
    "title": "iPhone 14 pro",
    "price": 479999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 147.5 x 71.5 x 7.9 mm (5.81 x 2.81 x 0.31 in) 206 g (7.27 oz) LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 14 pro.png",
},
{
    "id": 12,
    "title": "iPhone 14 pro max",
    "price":  574999,
    "description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 160.7 x 77.6 x 7.9 mm (6.33 x 3.06 x 0.31 in) 240 g (8.47 oz) LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM)",
    "brand": "Apple",
    "image": "/liberty electronics/images and video/images/Apple/iPhone 14 pro max.png",
},
// Samsung
{
"id": 13,
"title": "Samsung Galaxy A24 4G",
"price": " 72999",
"description": "It is fueled with a Li-Po 5000 mAh + 25W wired battery. Samsung Galaxy A24 4G features a 6.5 inches Super AMOLED that has a 1080 x 2340 pixels resolution. The device comes in various colors including Black, Lime Green, Blue gradient, and Dark red.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A24 4G.png",
},
{
"id": 14,
"title": "Samsung Galaxy A14",
"price": "56999",
"description": "Around the front is a teardrop notch for the 13-megapixel front-facing camera. In addition to its 1,080p resolution, the 6.6-inch display has a 90Hz refresh rate.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A14.png",
},
{
"id": 15,
"title": "Samsung Galaxy A23",
"price": "78499",
"description": "Octa-core processing power with up to 4GB/6GB/8GB of RAM for fast and efficient performance for the task at hand. Enjoy 64GB/128GB of internal storage and add up to 1TB more with MicroSD card.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A23.png",
},
{
"id": 16,
"title": "Samsung Galaxy A32",
"price": " 75999",
"description": "Pros: 1-super Amoled display 2-Light weight super handy 3-Great Media consumption 4-5000 mph battery enough for 1 day . Depends on usage . I am not a gaming person day to day use . 5- One ui gives you several security",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A32.png",
},
{
"id": 17,
"title": "Samsung Galaxy A52",
"price": " 65999",
"description": "It features an FHD+ 6.5-inch Super AMOLED display and a 4500 mAh battery with 25W super-fast charging. The Android OS is powered by an octa-core processor with 6GB RAM, and there's 128 GB of internal storage that's expandable to 1 TB via Micro SD. The handset is also IP67 rated for water and dust resistance.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A52.png",
},
{
"id": 18,
"title": "Samsung Galaxy A54",
"price": "140999",
"description": "6.4-inch display, an octa-core processor that offers enough power for daily essentials (including light gaming) and a camera that does a decent job of handling your out-and-about snaps.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A54.png",
},
{
"id": 19,
"title": "Samsung Galaxy Note9",
"price": " 139999",
"description": "Speed and Power: Galaxy Note9 is a super powerful smartphone with cutting-edge 10nm processor and support for the fastest network speeds available in the market (up to 1.2 gigabits per second), so you can stream and download without slowing dow",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy Note9.png",
},
{
"id": 20,
"title": "Samsung Galaxy S10",
"price": "139999",
"description": "The S10 features a 3-lens rear-facing camera setup; it retains the dual-aperture 12-megapixel and 12-megapixel telephoto lenses of the Galaxy S9+, but now uses a camera module introduced on the Note 9 and also adds a 16-megapixel ultra-wide angle lens.",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy S10.png",
},
{
"id": 21,
"title": "Samsung Galaxy S23 FE",
"price": "269999",
"description": "GSM / HSPA / LTE / 5G 158 x 76.5 x 8.2 mm (6.22 x 3.01 x 0.32 in) 209 g (7.37 oz) Dynamic AMOLED 2X, 120Hz, HDR10+, 1450 nits (peak)",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy S23 FE.png",
},
{
"id": 22,
"title": "Samsung Galaxy S23 Ultra",
"price": " 559999",
"description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 163.4 x 78.1 x 8.9 mm (6.43 x 3.07 x 0.35 in) 234 g (8.25 oz) Dynamic AMOLED 2X, 120Hz, HDR10+, 1200 nits (HBM), 1750 nits (peak)",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy S23 Ultra.png",
},
{
"id": 23,
"title": "Samsung Galaxy S23",
"price": "399999",
"description": "GSM / CDMA / HSPA / EVDO / LTE / 5G 146.3 x 70.9 x 7.6 mm (5.76 x 2.79 x 0.30 in) 168 g (5.93 oz) Dynamic AMOLED 2X, 120Hz, HDR10+, 1200 nits (HBM), 1750 nits (peak)",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy S23.png",
},
{
"id": 24,
"title": "Samsung Galaxy A34",
"price": "104999",
"description": "GSM / HSPA / LTE / 5G 161.3 x 78.1 x 8.2 mm (6.35 x 3.07 x 0.32 in) 199 g (7.02 oz) Super AMOLED, 120Hz, 1000 nits (HBM)",
"brand": "Samsung",
"image": "/liberty electronics/images and video/images/Samsung/Samsung Galaxy A34.png",
},
//Google Pixel
{
    "id": 25,
    "title": "Google Pixel 5a 5g",
    "price": "74999",
    "description": "The phone boasts an impressive 6.34-inch OLED display with an amazing refresh rate, providing crystal-clear visuals and smooth transitions. The Pixel 5a 5G is powered by a Qualcomm SM7250 Snapdragon 765G 5G chipset and comes with 6 GB of RAM, ensuring speedy performance even when running multiple apps simultaneously.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 5a 5g.png",
},
{
    "id": 26,
    "title": "Google Pixel 6 pro",
    "price": "124999",
    "description": "unique design and high-quality build, impressive display and good battery life, and its consistently good cameras and feature-rich software, the Google Pixel 6 Pro stands toe-to-toe with the very best from Apple and Samsung.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 6 pro.png",
},
{
    "id": 27,
    "title": "Google Pixel 6",
    "price": "106999",
    "description": " The Google Pixel 6 delivers the best Android experience for the money with superb cameras, a unique design and Android 12.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 6.png",
},
{
    "id": 28,
    "title": "Google Pixel 6a",
    "price": "86499",
    "description": "With a 6.1-inch display, the Pixel 6a isn't a small phone, but it's much more compact than the Pixel 6 and 6 Pro — closer to the iPhone 13. So, if you found the Pixel 6 to be big, this affordable alternative feels better.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 6a.png",
},
{
    "id": 29,
    "title": "Google Pixel 7",
    "price": "129999",
    "description": "Boasting features such as Photo Unblur and Clear Calling, Google Pixel just keeps getting better. From helping you photograph extraordinary moments to making it easier to catch up with friends, the new Pixel 7 features help you make and relive memories – like the picnic with friends, or even your baby's first steps.Boasting features such as Photo Unblur and Clear Calling, Google Pixel just keeps getting better. From helping you photograph extraordinary moments to making it easier to catch up with friends, the new Pixel 7 features help you make and relive memories – like the picnic with friends, or even your baby's first steps.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 7.png",
},
{
    "id": 30,
    "title": "Google Pixel 7a",
    "price": "137999",
    "description": "Pixel 7a brings amazing clarity and vibrant details to every photo  even in low light. With a 120° field of view, 6 get more of the landscape or fit more friends in the frame. Spend less time getting the perfect selfie with a 95° ultrawide field of view.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 7a.png",
},
{
    "id": 31,
    "title": "Google Pixel 7 pro",
    "price": "194000",
    "description": "The 7 Pro's screen is an expansive 6.7 inches, so roughly the same size as the iPhone 14 Plus and Samsung's S23 Ultra. It's crisp and smooth to use – fantastic for scrolling social media, watching YouTube and playing games – though we struggle to wield it with one hand.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 7 pro.png",
},
{
    "id": 32,
    "title": "Google Pixel 8 pro",
    "price": "253999",
    "description": "Fully upgraded cameras and never-before-seen editing. Polished aluminum frame and matte back glass. The power and brains behind Pixel 8 Pro. The new Google Tensor G3 chip is custom-designed with Google AI for cutting-edge photo and video features and smarter ways to help throughout the day.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 8 pro.png",
},
{
    "id": 33,
    "title": "Google Pixel 8",
    "price": "163999",
    "description": "Pixel 8, with its contoured edges and smaller size than Pixel 7, feels great in your hand. It has a 6.2-inch Actua display, which gives you real-world clarity and is 42% brighter than Pixel 7's display. Pixel 8 features satin metal finishes, a polished glass back and comes in Rose, Hazel and Obsidian",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 8.png",
},
{
    "id": 34,
    "title": "Google Pixel Fold",
    "price": "454999",
    "description": "A full 5.8 Pixel phone when it s folded. Unfolded, you get a 7.6 immersive display. The most durable hinge on a foldable. And the thinnest foldable of all.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel Fold.png",
},
{
    "id": 35,
    "title": "Google Pixel 4a",
    "price": "116999",
    "description": "The Pixel 4a now flaunts an OLED display with HDR10 support. The smartphone features a single 12MP rear camera and an 8MP front snapper. Under the hood is a Snapdragon 730G SoC with 6GB RAM and 128GB storage. Google launched three new Pixel smartphones in 2020",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 4a.png",
},
{
    "id": 36,
    "title": "Google Pixel 5 5g",
    "price": "186999",
    "description": "The phone is powered by the Snapdragon 765G chipset, which supports 5G, 8GB RAM, and 128GB storage. There are a dual-camera setup and a fingerprint on the back. A 6-inch OLED display with a 90Hz refresh rate and 8MP selfie camera are presented at the front. Google Pixel 5 is powered by a 4080mAh battery and Android 11.",
    "brand": "Google Pixel",
    "image": "/liberty electronics/images and video/images/Google Pixel/Google Pixel 5 5g.png",
},
//Huawei
{
    "id": 37,
    "title": "Huawei Enjoy 60 X",
    "price": "64999",
    "description": "The smartphone comes with a 6.95 inches TFT LCD capacitive touchscreen and 1080 x 2376 pixels resolution. The dimension of the device is 171.6 x 79.9 x 8.9 mm and it weighs 216 grams. The rear camera consists of a dual camera: 50 MP (wide) + 2 MP (depth) sensor lenses. The front camera has a 8 MP (wide) sensor.",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei Enjoy 60 X.png",
},
{
    "id": 38,
    "title": "Huawei mate 60 plus",
    "price": "229999",
    "description": "The smartphone is pack with 16 GB RAM and 512 GB, 1 TB internal storage. The device comes with a LTPO OLED 6.82 inches screen size and the resolution is 1260 x 2720 pixels. The display is protected by Huawei Kunlun Glass 2 and it supports IP68 dust/water resistant (up to 6m for 30 min).",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei mate 60 plus.png",
},
{
    "id": 39,
    "title": "Huawei mate 60 pro",
    "price": "112799",
    "description": "The smartphone is pack with 16 GB RAM and 512 GB, 1 TB internal storage. The device comes with a LTPO OLED 6.82 inches screen size and the resolution is 1260 x 2720 pixels. The display is protected by Huawei Kunlun Glass 2 and it supports IP68 dust/water resistant (up to 6m for 30 min).",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei mate 60 pro.png",
},
{
    "id": 40,
    "title": "Huawei mate 60 rs ultimate",
    "price": "455920",
    "description": "The smartphone is pack with 16 GB RAM and 512 GB, 1 TB internal storage. The device comes with a LTPO OLED 6.82 inches screen size and the resolution is 1260 x 2720 pixels. The display is protected by Huawei Kunlun Glass 2 and it supports IP68 dust/water resistant (up to 6m for 30 min).",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei mate 60 rs ultimate.png",
},
{
    "id": 41,
    "title": "Huawei mate 60",
    "price": "112799",
    "description": "The smartphone is pack with 12 GB RAM and 256 GB, 512 GB, 1 TB internal storage. The device comes with an OLED 6.82 inches screen size and the resolution is 1212 x 2616 pixels. The display is protected by Huawei Kunlun Glass 2 and it supports IP68 dust/water resistant (up to 6m for 30 min).",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei mate 60.png",
},
{
    "id": 42,
    "title": "Huawei nova 10 se",
    "price": "128999",
    "description": "Huawei nova 10 SE has been officially announced on Oct. 5, 2022. The size of the screen is 6.67 inches and it provides a resolution of 1080 x 2400 pixels with 90Hz and 1B colors. The screen type is OLED capacitive touchscreen.",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 10 se.png",
},
{
    "id": 43,
    "title": "Huawei nova 11 pro",
    "price": "139000",
    "description": "Huawei nova 11 Pro smartphone. Announced Apr 2023. Features 6.78″ display, Snapdragon 778G 4G chipset, 4500 mAh battery, 512 GB storage, 8 GB RAM",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 11 pro.png",
},
{
    "id": 44,
    "title": "Huawei nova 11 se",
    "price": "73999",
    "description": "The rear side features triple-camera: 108 MP (wide) + 8 MP (ultrawide) + 2 MP (macro) while on the front also it comes with a single camera: 32 MP (wide). The smartphone is packed with 256 GB, 512 GB internal storage. The dimension of the device is 162.4 x 75.5 x 7.4 mm and it weighs 186 grams.",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 11 se.png",
},
{
    "id": 45,
    "title": "Huawei nova 11 ultra",
    "price": "166100",
    "description": "It is fueled with 4500 mAh battery + 100W wired, 50% in 15 min (advertised) + Reverse wired. The rear side features dual-camera: 50 MP (wide) + 8 MP (ultrawide) while on the front also it comes with a dual camera: 8 MP (portrait) + 60 MP (ultrawide).",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 11 ultra.png",
},
{
    "id": 46,
    "title": "Huawei nova 11",
    "price": "100636",
    "description": "HUAWEI nova 11 Smart Phone, 6.88 mm Ultra-thin Design, 60 MP Front Ultra Wide Portrait Camera, 50 MP Ultra Vision Photography, 66 W HUAWEI SuperCharge Turbo, 6.7-inch OLED Display, 8+256GB, Gold.",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 11.png",
},
{
    "id": 47,
    "title": "Huawei nova 11i",
    "price": "84790",
    "description": "HUAWEI nova 11i Specification · Display. Screen Size: 6.8 inches · Processor. Qualcomm Snapdragon™ 680. CPU: · Operating System. EMUI 13 · Memory. 8 GB RAM + 128 GB ",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova 11i.png",
},
{
    "id": 48,
    "title": "Huawei nova y 71",
    "price": "56990",
    "description": "With 6.75-inch HUAWEI FullView Display3, and 90.26% screen-to-body ratio7, HUAWEI nova Y71 makes watching blockbusters more immersive. Settle in for your binge watching, and stay glued for every glimpse, thanks to smart, eye-soothing ambient light adjustments.",
    "brand": "Huawei",
    "image": "/liberty electronics/images and video/images/Huawei/Huawei nova y 71.png",
},
//Oppo
{
    "id": 49,
    "title": "Oppo a1 5g",
    "price": "73999",
    "description": "The Oppo A1 5G runs Android 13 and is powered by a 5000mAh non-removable battery. The Oppo A1 5G supports Super VOOC fast charging. As far as the cameras are concerned, the Oppo A1 5G on the rear packs a dual camera setup featuring a 50-megapixel primary camera, and a 2-megapixel camera.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a1 5g.png",
},
{
    "id": 50,
    "title": "Oppo a1 pro",
    "price": "73999",
    "description": "The device is packed with 3 GB RAM with 64 GB internal storage, which can be increased with microSDXC. The device consists of a single camera: 8 MP (wide). On the front, there is a 5 MP (wide) camera for clicking selfies. The size of the display is 6.56 inches IPS LCD while the screen resolution is 720 x 1612 pixels.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a1 pro.png",
},
{
    "id": 51,
    "title": "Oppo a2 pro",
    "price": "71170",
    "description": "OPPO A2 Pro has a good appearance design, paying tribute to the flagship of the  design is very delicate, 3D hyperbolic body can also give you a comfortable grip feel; 6.7-inch dual-curved eye protection screen, 120Hz high refresh rate and 2160Hz ultra-high frequency PWM dimming, ",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a2 pro.png",
},
{
    "id": 52,
    "title": "Oppo a2 ",
    "price": "78999",
    "description": "Boasting an impressive 512GB storage option at an affordable price point, the phone is now available for reservations, with pre-sales commencing on November 6. The OPPO A2 features a 6.72-inch 2.5D LCD screen that supports a 90Hz refresh rate, offering users a vibrant visual experience.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a2.png",
},
{
    "id": 53,
    "title": "Oppo a38",
    "price": "49999",
    "description": "OPPO A38 arrives with 33W SUPERVOOC, 5000mAh Large Battery, 4GB + Up to 4GB Extented RAM, 90Hz Sunlight Display, 50MP AI camera, 36-Month Fluency",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a38.png",
},
{
    "id": 54,
    "title": "Oppo a58 4g",
    "price": "45800",
    "description": "The smartphone is powered by Mediatek MT6769 Helio G85 Octa-core processor with Mali-G52 MC2 GPU. The device runs on Android 13 + ColorOS 13.1 operating system.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a58 4g.png",
},
{
    "id": 55,
    "title": "Oppo a78 4g",
    "price": "61160",
    "description": "The OPPO A78 4G comes with stereo speakers and an in-display fingerprint sensor. It supports Dual 4G VoLTE, Wi-Fi 802.11 ac (2.4GHz + 5GHz), Bluetooth 5.0, GPS, and USB Type-C connectivity. The device houses a 5000mAh battery with 67W SuperVOOC fast charging.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo a78 4g.png",
},
{
    "id": 56,
    "title": "Oppo Find n3 Flip",
    "price": "328999",
    "description": "The Oppo Find N3 Flip has a 3.26-inch cover display with a 720x382 resolution, and on the inside is a 6.8-inch AMOLED screen with a clear 2520x1080 resolution. The cover screen supports over 40 popular apps like Google Maps, WhatsApp, Twitter, and more, and they work seamlessly without distortions or black bars.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo Find n3 Flip.png",
},
{
    "id": 57,
    "title": "Oppo k11 5g",
    "price": "73999",
    "description": "Oppo K11 5G mobile was launched on 25th July 2023. The phone comes with a 6.70-inch touchscreen display offering a resolution of 2400x1080 pixels (FHD+) at a pixel density of 394 pixels per inch (ppi). Oppo K11 5G is powered by an octa-core Snapdragon 782G processor. It comes with 8GB of RAM.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo k11 5g.png",
},
{
    "id": 58,
    "title": "Oppo Reno 10 pro plus",
    "price": "134999",
    "description": "The smartphone comes with a rear triple-camera set up with a 50 MP (wide) + 64 MP (periscope telephoto) + 8 MP (ultrawide). On the front, there is a single camera of 32 MP (wide) for your selfies. OPPO Reno 10 Pro Plus is fueled by a Li-Po 4700 mAh battery + 100W wired, PD, QC3 + Reverse wired.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo Reno 10 pro plus.png",
},
{
    "id": 59,
    "title": "Oppo Reno 10 pro",
    "price": "119999",
    "description": "6.7-inch full HD+ display, Qualcomm Snapdragon 778G SoC, 12GB RAM, 256GB storage, 50MP + 8MP + 32MP camera, ColorOS, 4600mAh battery, 80W fast charging. The premium and elegant design of the flagship counterpart, Reno 10 Pro +, has been carried over to the slightly more affordable Reno 10 Pro model.",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo Reno 10 pro.png",
},
{
    "id": 60,
    "title": "Oppo Reno 10",
    "price": "89999",
    "description": "OPPO Reno10 5G (CPH2531) · Size and Weight. Height. about 162.43mm · Storage. RAM and ROM Capacities. 8GB + 128GB · Display. Size. 6.7 · Camera. Rear",
    "brand": "Oppo",
    "image": "/liberty electronics/images and video/images/Oppo/Oppo Reno 10.png",
},
// Tecno
{
    "id": 61,
    "title": "Tecno camon20 pro 5g",
    "price": "82999",
    "description": "Tecno Camon 20 Pro 5G mobile was launched on 27th May 2023. The phone comes with a 120 Hz refresh rate 6.67-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). Tecno Camon 20 Pro 5G is powered by an octa-core MediaTek Dimensity 8050 processor.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno camon20 pro 5g.png",
},
{
    "id": 62,
    "title": "Tecno camon20 pro",
    "price": "60999",
    "description": "6.67-inch AMOLED Capacitive touchscreen display with a resolution of 1080 x 2400 pixels and a refresh rate of 120 Hz. With the Camon 20 Pro, you will be able to use it all day using just a single charge since it is equipped with a 5000 mAh battery.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno camon20 pro.png",
},
{
    "id": 63,
    "title": "Tecno camon20",
    "price": "49999",
    "description": "Powered by the MediaTek Helio G85 chipset and an Octa-core CPU, this device ensures smooth and efficient performance. Capture life's moments in stunning detail with a triple camera setup featuring a 64MP main sensor. With a 5000mAh big battery that supports 33W fast charging, you can stay connected all day long.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno camon20.png",
},
{
    "id": 64,
    "title": "Tecno pop7",
    "price": "25999",
    "description": "The smartphone is fueled by a non-removable Li-Ion 5000 mAh battery + 10W wired while the phone runs on Android 12 + HIOS 12 operating system. Tecno Pop 7 comes in two colors: Endless Black, Capri Blue. It features USB, FM radio, GPS, and Bluetooth. The device is packed with 2 GB RAM with 64 GB internal storage.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pop7.png",
},
{
    "id": 65,
    "title": "Tecno pop8",
    "price": "27999",
    "description": "The smartphone is fueled by a non-removable Li-Ion 5000 mAh battery + 10W wired while the phone runs on Android 12 + HIOS 12 operating system. Tecno Pop 7 comes in two colors: Endless Black, Capri Blue. It features USB, FM radio, GPS, and Bluetooth. The device is packed with 2 GB RAM with 64 GB internal storage.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pop8.png",
},
{
    "id": 66,
    "title": "Tecno pova 4 pro",
    "price": "21999",
    "description": "Tecno Pova 4 Pro is powered by an octa-core MediaTek Helio G99 processor. It comes with 8GB of RAM. As far as the cameras are concerned, the Tecno Pova 4 Pro on the rear packs a dual camera setup featuring a 50-megapixel primary camera, and a 2-megapixel camera.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pova 4 pro.png",
},
{
    "id": 67,
    "title": "Tecno pova neo 2",
    "price": "39799",
    "description": "Tecno Pova Neo 2 mobile was launched in September 2022. The phone comes with a 90 Hz refresh rate 6.82-inch touchscreen display offering a resolution of 720x1640 pixels (FHD+) and an aspect ratio of 20:9. Tecno Pova Neo 2 is powered by an octa-core MediaTek Helio G85 processor.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pova neo 2.png",
},
{
    "id": 68,
    "title": "Tecno pova neo 3",
    "price": "54999",
    "description": "It is packed with 4 GB, 8 GB RAM while the internal storage option is 128 GB. The device features Bluetooth, FM Radio, GPS, and micro USB 2.0, USB On-The-Go. The dimension of the device is 170.7 x 77.6 x 9.3 mm. The smartphone runs on the Android 13 + HIOS operating system.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pova neo 3.png",
},
{
    "id": 69,
    "title": "Tecno pova5 pro",
    "price": "44999",
    "description": "The Tecno Pova 5 Pro 5G comes with a 6.78-inch display with an FHD+ resolution and an adaptive 120Hz refresh rate. It packs a 50MP AI dual-camera at the back, and a 16MP front camera. It is powered by the octa-core MediaTek Dimensity 6080 5G chipset and runs on a large 5000mAh battery.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pova5 pro.png",
},
{
    "id": 70,
    "title": "Tecno pova5",
    "price": "42999",
    "description": "The Tecno Pova 5 Pro 5G comes with a 6.78-inch display with an FHD+ resolution and an adaptive 120Hz refresh rate. It packs a 50MP AI dual-camera at the back, and a 16MP front camera. It is powered by the octa-core MediaTek Dimensity 6080 5G chipset and runs on a large 5000mAh battery.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno pova5.png",
},
{
    "id": 71,
    "title": "Tecno spark 10",
    "price": "30999",
    "description": "The dimension of the smartphone is 163.9 x 75.4 x 8.4 mm. It is built with a glass front, plastic frame, and glass back. The rear camera consists of 50 MP (wide) + other unspecified camera that comes with a Dual-LED flash. The front camera has a 8 MP (wide) sensor with a LED flash.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno spark 10.png",
},
{
    "id": 72,
    "title": "Tecno spark10 5g",
    "price": "39999",
    "description": "Tecno Spark 10 5G Android smartphone. Announced Mar 2023. Features 6.6″ display, Dimensity 6020 chipset, 5000 mAh battery, 256 GB storage, 8 GB RAM.",
    "brand": "Tecno",
    "image": "/liberty electronics/images and video/images/Tecno/Tecno spark10 5g.png",
},
//Motorola
{
    "id": 73,
    "title": "Motorola defy 2",
    "price": "49999",
    "description": "Motorola Defy 2 is fueled with a non-removable Li-Po 5000 mAh battery + 15W wireless. The dimension of the device is 171 x 80 x 11.9 mm and it weighs 268 grams ",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola defy 2.png",
},
{
    "id": 74,
    "title": "Motorola edge 30 ultra",
    "price": "210999",
    "description": "The smartphone is packed with 8 GB and 12 GB RAM with 128 GB, 256 GB and 512 GB internal storage. It comes with a powerful Non-removable Li-Po 4610 mAh battery + Fast charging 125W + Fast wireless charging 50W + Reverse wireless charging 10W.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola edge 30 ultra.png",
},

{
    "id": 75,
    "title": "Motorola edge 40 neo",
    "price": "98999",
    "description": "The Motorola Edge 40 Neo is an affordable alternative to the Motorola Edge 40 available to buy online now for $579/£299. Currently, only one Pros and cons IP68 water and dustproof  6.55 inch OLED display 144Hz A little slow running",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola edge 40 neo.png",
},

{
    "id": 76,
    "title": "Motorola edge 40",
    "price": "191999",
    "description": "The Moto Edge 40 treats users to a fairly generous 6.55-inch display which features a full HD resolution of 1080 x 2400. It's driven by P-OLED technology and can produce a peak max brightness of 1200 nits. Its refresh rate also hits up to 144Hz for nice smooth scrolling, and even for gaming if you're that way inclined.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola edge 40.png",
},

{
    "id": 77,
    "title": "Motorola g14",
    "price": "36140",
    "description": "Elegance with a splash. Crafted with high-quality materials for a premium look and feel, moto g14 also features a special edition made from vegan leather that's soft to the touch and fingerprint-resistant. Plus, a water-repellent2 frame protects from spills and splashes.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola g14.png",
},

{
    "id": 78,
    "title": "Motorola moto e13",
    "price": "32999",
    "description": "The Motorola Moto E13 is powered by 1.6 GHz Octa-core processor and it comes with 2GB of RAM. The Motorola Moto E13 packs 64GB of internal storage that can be expanded via microSDXC (uses shared SIM slot). The Motorola Moto E13 runs Android 13 and is powered by a Li-Ion 5000 mAh non-removable battery.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola moto e13.png",
},

{
    "id": 79,
    "title": "Motorola moto g53",
    "price": "39999",
    "description": "The Motorola Moto G53 is powered by 2.2 GHz Octa-core processor and it comes with 4GB of RAM. The Motorola Moto G53 packs 128GB of internal storage that cannot be expanded. The Motorola Moto G53 runs Android 13 and is powered by a 5000mAh non-removable battery.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola moto g53.png",
},

{
    "id": 80,
    "title": "Motorola moto g54 10",
    "price": "43999",
    "description": "The Moto G54 is powered by the MediaTek Dimensity 7020 processor and has a 6000mAh battery. There is a 50-megapixel main camera, complete with optical image stabilization. There are three colour options - two shades of blue and one green. The hero of this review is the base variant of the G54 in deep blue shade.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola moto g54 10.png",
},

{
    "id": 81,
    "title": "Motorola moto g73",
    "price": "56999",
    "description": "A 120Hz screen, solid performance, long battery life, a 50MP camera and a stylish design – on paper, the Motorola Moto G73 5G has everything a good mid-tier smartphone needs. For slightly under €300 (US$330), you are also getting an almost stock Android 13 and plenty of storage.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola moto g73.png",
},

{
    "id": 82,
    "title": "Motorola moto g84",
    "price": "80699",
    "description": "Motorola Moto G84 is packed with 8 GB, 12 GB RAM with 256 GB internal storage. It also supports IP54, dust and splash resistant. It comes with a powerful non-removable Li-Po 5000 mAh battery + 18W wired + 30W wired. The smartphone is powered by a Qualcomm SM6375 Snapdragon 695 5G octa-core.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola moto g84.png",
},

{
    "id": 83,
    "title": "Motorola razr 40 ultra",
    "price": "361999",
    "description": "The Motorola Razr 40 Ultra features a sleek design, impressive displays, best-in class selfie shooters and smooth performance. While the inner OLED display delivers vibrant visuals and larger screen estate, the cover screen can be used to perform various tasks without needing to open the phone.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola razr 40 ultra.png",
},

{
    "id": 84,
    "title": "Motorola razr 40",
    "price": "169999",
    "description": "This 3.6-inch pOLED display with 1066 x 1056 resolution boasts a 144Hz refresh rate, 1,100 nits of max brightness, HDR10+ support and 100% DCI-P3 colour gamut coverage. In Motorola's words, it's the “largest, most advanced external display of any flip phone,” and it certainly takes the cake.",
    "brand": "Motorola",
    "image": "/liberty electronics/images and video/images/Motorola/Motorola razr 40.png",
},
//Infinix
{
    "id": 85,
    "title": "Infinix g10 pro 5g",
    "price": "69999",
    "description": "Infinix GT 10 Pro Android smartphone. Announced Aug 2023. Features 6.67″ display, Dimensity 8050 chipset, 5000 mAh battery, 256 GB storage, 8 GB RAM.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix g10 pro 5g.png",
},
{
    "id": 86,
    "title": "Infinix hot 30 5g",
    "price": "44999",
    "description": "The Infinix Hot 30 is the company's most recent flagship device. It has a 6.78-inch AMOLED display with a refresh rate of 120Hz and a pixel density of 396 PPI. The gadget was powered by the MediaTek Dimensity 6020 (7 nm) 5G chipset, paired with 8GB of RAM and 256GB of storage.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix hot 30 5g.png",
},
{
    "id": 87,
    "title": "Infinix hot 30 play NFC",
    "price": "31999",
    "description": "As the name suggests, Infinix Hot 30 Play NFC features near-field communication technology for payments and more. The phone boots XOS 12.6 based on Android 13 and features a side-mounted fingerprint scanner. Infinix Hot 30 Play NFC comes in Mirage Black, Blade White and Bora Purple colors.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix hot 30 play NFC.png",
},
{
    "id": 88,
    "title": "Infinix hot 30i",
    "price": "29999",
    "description": "The phone comes with a 90 Hz refresh rate 6.60-inch touchscreen display (FHD+). It comes with 16GB of RAM. The Infinix Hot 30i runs Android 12 and is powered by a 5000mAh battery. The Infinix Hot 30i supports proprietary fast charging.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix hot 30i.png",
},
{
    "id": 89,
    "title": "Infinix note 30 4g",
    "price": "49999",
    "description": "The device is fueled with a non-removable Li-Po 5000 mAh battery + 45W wired. The smartphone is powered by a Mediatek MT8781 Helio G99 Octa-core processor and Mali-G57 MC2 GPU. It comes in a big screen that has a 6.78 inches display AMOLED capacitive touchscreen with a resolution of 1080 x 2400 pixels.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix note 30 4g.png",
},
{
    "id": 90,
    "title": "Infinix note 30 pro",
    "price": "74999",
    "description": "The Infinix NOTE 30 Pro has a 5000 mAh battery, fast and wireless charging, an attractive design (like more expensive smartphones), mega-colour, 120Hz AMOLED screen, fast interface and good cameras. The Infinix Note 30 Pro is a decent smartphone entry into 2023.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix note 30 pro.png",
},
{
    "id": 91,
    "title": "Infinix note 30i 4g",
    "price": "30580",
    "description": "The phone supports dual SIM and features a dual camera that consists of 64 MP (wide) + QVGA with Quad-LED flash. The front camera consists of a single camera: 16 MP. Infinix Note 30i comes with a loudspeaker (dual speakers) and a 3.5mm jack. The smartphone features Bluetooth, GPS, and Type-C 2.0, USB On-The-Go.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix note 30i 4g.png",
},
{
    "id": 92,
    "title": "Infinix smart7 HD",
    "price": "20999",
    "description": "Infinix Smart 7 HD features dual-camera that consists of 8 MP (wide) + 0.08 MP (depth) with Dual-LED flash. The front camera consists of a single camera: 5 MP. The smartphone is enabled with Bluetooth 5.0, GPS, FM Radio, and microUSB 2.0, OTG. The sensors include rear-mounted fingerprint, accelerometer, and proximity.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix smart7 HD.png",
},
{
    "id": 93,
    "title": "Infinix x6710 note 30 VIP",
    "price": "74999",
    "description": "6.78 inches, 111.0 cm, 1080 x 2400 pixels, 20:9 ratio (~388 ppi density), the display diagonal size and resolution is unconfirmed. QUAD FLASH LIGHT. 32 MP, DUAL FLASH LIGHT. Fingerprint (side-mounted), accelerometer, gyro, proximity, compass.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix x6710 note 30 VIP.png",
},
{
    "id": 94,
    "title": "Infinix zero 20",
    "price": "79999",
    "description": "It comes in a big screen that has a 6.7 inches display AMOLED with a resolution of 1080 x 2400 pixels. It comes in different colors like Space Gray, Glitter Gold, and Green Fantasy. The device is fueled with a non-removable Li-Po 4500 mAh battery + Fast Charging 45W, 75% in 30 min (advertised).",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix zero 20.png",
},
{
    "id": 95,
    "title": "Infinix zero 30 4g",
    "price": " 59999",
    "description": "Infinix Zero 30 4G features triple-camera that consists of 108 MP (wide) + 2 MP + 2 MP. The front camera consists of a single camera: 50 MP (wide). The smartphone is integrated with a loudspeaker. The smartphone is enabled with Bluetooth, A-GPS, FM Radio, and USB Type-C 2.0.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix zero 30 4g.png",
},
{
    "id": 96,
    "title": "Infinix zero 30 5g",
    "price": "59999",
    "description": "The phone comes with a 144 Hz refresh rate 6.78-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). The display sports Gorilla Glass for protection. Infinix Zero 30 5G is powered by an octa-core MediaTek Dimensity 8020 processor.",
    "brand": "Infinix",
    "image": "/liberty electronics/images and video/images/Infinix/Infinix zero 30 5g.png",
},
]